global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'postgres_exporter'
    static_configs:
      - targets: ['postgres_exporter:9187']

  - job_name: 'sparknode-backend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']

  - job_name: 'sparknode-frontend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['frontend:80']

  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100']
